services:
  node0:
    image: blockchat
    environment:
      - NODE_ID=0
    env_file:
      - ./.env
    networks:
      - cluster

  node1:
    image: blockchat
    environment:
      - NODE_ID=1
    env_file:
      - ./.env
    networks:
      - cluster
    depends_on:
      - node0

networks:
  cluster:
    external: true