services:
  node0:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - NODE_ID=0
    env_file:
      - ./.env
  node1:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - NODE_ID=1
    env_file:
      - ./.env
  node2:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - NODE_ID=2
    env_file:
      - ./.env