services:
  node0:
    image: blockchat
    environment:
      - NODE_ID=0
      # - INPUT_PATH=./input/trans0.txt
    env_file:
      - ./docker.env
    networks:
      - cluster
    ports:
      - "1500:1500"
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS}

  node1:
    image: blockchat
    environment:
      - NODE_ID=1
      # - INPUT_PATH=./input/trans1.txt
    env_file:
      - ./docker.env
    networks:
      - cluster
    ports:
      - "1501:1500"
    logging:
      driver: gelf
      options:
        gelf-address: udp://snf-43711.ok-kno.grnetcloud.net:12201

  node2:
    image: blockchat
    environment:
      - NODE_ID=2
      # - INPUT_PATH=./input/trans2.txt
    env_file:
      - ./docker.env
    networks:
      - cluster
    ports:
      - "1502:1500"
    logging:
      driver: gelf
      options:
        gelf-address: udp://snf-43711.ok-kno.grnetcloud.net:12201

  node3:
    image: blockchat
    environment:
      - NODE_ID=3
      # - INPUT_PATH=./input/trans3.txt
    env_file:
      - ./docker.env
    networks:
      - cluster
    ports:
      - "1503:1500"
    logging:
      driver: gelf
      options:
        gelf-address: udp://snf-43711.ok-kno.grnetcloud.net:12201

  node4:
    image: blockchat
    environment:
      - NODE_ID=4
      # - INPUT_PATH=./input/trans4.txt
    env_file:
      - ./docker.env
    networks:
      - cluster
    ports:
      - "1504:1500"
    logging:
      driver: gelf
      options:
        gelf-address: udp://snf-43711.ok-kno.grnetcloud.net:12201
    
  node5:
    image: blockchat
    environment:
      - NODE_ID=5
      # - INPUT_PATH=./input/trans5.txt
    env_file:
      - ./docker.env
    networks:
      - cluster
    ports:
      - "1505:1500"
    logging:
      driver: gelf
      options:
        gelf-address: udp://snf-43711.ok-kno.grnetcloud.net:12201
    

  node6:
    image: blockchat
    environment:
      - NODE_ID=6
      # - INPUT_PATH=./input/trans6.txt
    env_file:
      - ./docker.env
    networks:
      - cluster
    ports:
      - "1506:1500"
    logging:
      driver: gelf
      options:
        gelf-address: udp://snf-43711.ok-kno.grnetcloud.net:12201

  node7:
    image: blockchat
    environment:
      - NODE_ID=7
      # - INPUT_PATH=./input/trans7.txt
    env_file:
      - ./docker.env
    networks:
      - cluster
    ports:
      - "1507:1500"
    logging:
      driver: gelf
      options:
        gelf-address: udp://snf-43711.ok-kno.grnetcloud.net:12201


  node8:
    image: blockchat
    environment:
      - NODE_ID=8
      # - INPUT_PATH=./input/trans8.txt
    env_file:
      - ./docker.env
    networks:
      - cluster
    ports:
      - "1508:1500"
    logging:
      driver: gelf
      options:
        gelf-address: udp://snf-43711.ok-kno.grnetcloud.net:12201

  node9:
    image: blockchat
    environment:
      - NODE_ID=9
      # - INPUT_PATH=./input/trans9.txt
    env_file:
      - ./docker.env
    networks:
      - cluster
    ports:
      - "1509:1500"
    logging:
      driver: gelf
      options:
        gelf-address: udp://snf-43711.ok-kno.grnetcloud.net:12201
        
networks:
  cluster:
    external: true